### ISSUE TITLE
Problem during installation of Digilent Boards in Arduino Studio

### ISSUE THREAD

**Issue by BluDotz** [Digilent/openscope-mz#3]
I want to modify the OpenScopeMZ firmware, and so followed the instructions in README.md.

However I have got no further than step 2, because an error occurs when the tools are being downloaded from AWS. 

When I access the corresponding page through my browser the error message is as follows:

**`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>Software/Digilent_Core/xc32-tools/1.43</Key>
<RequestId>26300E2565E7A2C4</RequestId>
<HostId>
x/UmKN0/KiuFEWfzDS7lcN6IKNVKMm3ENH3G0tmJe/EcusNOy8cm+uUETCYSGmGHTwZ/XJKe0ww=
</HostId>
</Error>`**

Perhaps your AWS credentials are out-of-date?

**Comment by samkristoff** [comment]
Hey BluDotz, I just tested this and it works for me.  Can you post on the [Digilent Forums](https://forum.digilentinc.com/forum/30-waveforms-live-and-openscope-mz/) so we can help troubleshoot this.

Thanks!

**Comment by BluDotz** [comment]
WILCO

**Comment by samkristoff** [comment]
Conversation moved [here](https://forum.digilentinc.com/topic/4360-problems-with-arduino-studio-boards-manager/).

**Comment by samkristoff** [comment]
Resolved by deleting the Digilent files in : /Users/<USERNAME>/Library/Arduino15/staging/packages and using Arduino 1.6.9.  

I have 4 files after a clean install that start with the following prefixes

chipKIT*
Digilent*
xc32*

Close and re-open the Arduino IDE after deleting files.
