### ISSUE TITLE
Unable to set gain at 5v/div

### ISSUE THREAD

**Issue by samkristoff** [Digilent/openscope-mz#5]
[Reported in 1.4.0](https://forum.digilentinc.com/topic/4422-error-in-setting-2vdiv/)

**Comment by VictorTagayun** [comment]
Seems to be working now.... Not sure what version of WaveformsLive it is...

**Comment by samkristoff** [comment]
Fixed in firmware version 1.37.0.  Fix does not depend on a specific version of WaveForms Live.
