### ISSUE TITLE
XCLM: Failed to elevate privilege - is the XCLM binary setuid-root?

### ISSUE THREAD

**Issue by yanghao** [Digilent/openscope-mz#8]
Just in case any one hit the same issue with arduino on Linux, there were solutions to re-install everything as root (https://forum.digilentinc.com/topic/5423-uc-32-failed-to-compile-blink-sketch/), the actual fix is just to make sure xclm being able to run as root:

```
$ cd ~/.arduino15/packages/Digilent/tools/xc32-tools/xc32-1.43/bin
$ sudo su
# chown root.root ./xclm
# chmod 4777 ./xclm
```

This should fix the issue as in the title.

**Comment by TheEtwolf** [comment]
Thank you.
